Repository sunpy/sunraster, pull requests merged in 2020-04, with the labels that each got.

#139 Make RasterSequence aware of instrument axis types: 2nd attempt
  changelog/139.breaking.rst
  docs/data_classes.rst
  setup.cfg
  sunraster/__init__.py
  sunraster/instr/iris/tests/test_iris_tools.py
  sunraster/instr/iris/tests/test_obsid.py
  sunraster/instr/iris/tests/test_sji.py
  sunraster/instr/iris/tests/test_spectrograph.py
  sunraster/raster.py
  sunraster/raster_sequence.py
  sunraster/tests/test_raster.py
  sunraster/tests/test_rastersequence.py
  sunraster/utils/sequence.py
Labels: sunraster

#150 Reimplement basic RasterSequence slicing API
  sunraster/spectrogram_sequence.py
Labels: sunraster

#154 CI build for ndcube 1.3 branch
  .circleci/config.yml
  .codecov.yaml
  azure-pipelines.yml
  docs/api.rst
  docs/conf.py
  docs/contributing.rst
  docs/data_classes.rst
  sunraster/__init__.py
  sunraster/io/iris.py
  sunraster/spectrogram.py
  sunraster/spectrogram_sequence.py
  sunraster/tests/test_spectrogram.py
  sunraster/tests/test_spectrogramsequence.py
  tox.ini
Labels: No Changelog Entry Needed

#156 Improve Test coverage and Remove utils
  sunraster/spectrogram.py
  sunraster/spectrogram_sequence.py
  sunraster/tests/test_spectrogram.py
  sunraster/tests/test_spectrogramsequence.py
  sunraster/utils/__init__.py
  sunraster/utils/sequence.py
Labels: No Changelog Entry Needed, sunraster

#158 Update Docs for new SpectrogramSequence class
  docs/data_classes.rst
  sunraster/spectrogram.py
  sunraster/tests/test_spectrogram.py
Labels: No Changelog Entry Needed, sunraster

#159 non-conda on rtd
  .readthedocs.yml
  .rtd-environment.yml
  readthedocs.yml
Labels: No Changelog Entry Needed

#160 Proofreading of sunraster docs
  README.rst
  docs/contributing.rst
  docs/data_classes.rst
  docs/index.rst
  docs/installation.rst
  docs/introduction.rst
Labels: No Changelog Entry Needed, sunraster

#161 Remove erroneous indentation.
  docs/data_classes.rst
Labels: No Changelog Entry Needed, sunraster

#164 Update install dependencies
  setup.cfg
Labels: No Changelog Entry Needed
